function Jv = Jacobian_youbot(d2,d3,d4,lend,th1,th2,th3,th4)
%JACOBIAN_YOUBOT
%    JV = JACOBIAN_YOUBOT(D2,D3,D4,LEND,TH1,TH2,TH3,TH4)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    22-Mar-2017 16:25:01

t2 = -th1+th2+th3;
t3 = cos(t2);
t4 = th1+th2+th3+th4;
t5 = cos(t4);
t6 = lend.*t5.*5.0e-1;
t7 = th1+th2;
t8 = cos(t7);
t9 = d3.*t8.*5.0e-1;
t10 = -th1+th2+th3+th4;
t11 = cos(t10);
t12 = th1-th2;
t13 = cos(t12);
t14 = th1+th2+th3;
t15 = cos(t14);
t16 = d4.*t15.*5.0e-1;
t17 = d4.*t3.*5.0e-1;
t18 = lend.*t11.*5.0e-1;
t19 = cos(th1);
t20 = sin(th1);
t21 = sin(t2);
t22 = sin(t4);
t23 = sin(t7);
t24 = sin(t10);
t25 = sin(t12);
t26 = d3.*t25.*5.0e-1;
t27 = sin(t14);
t28 = d4.*t21.*5.0e-1;
t29 = lend.*t24.*5.0e-1;
t30 = th2+th3;
t31 = sin(t30);
t32 = th2+th3+th4;
t33 = sin(t32);
Jv = reshape([t6+t9+t16-d4.*t3.*5.0e-1-d3.*t13.*5.0e-1-d2.*t20-lend.*t11.*5.0e-1-lend.*t19.*6.123233995736766e-17,t26-d2.*t19-d4.*t21.*5.0e-1-d3.*t23.*5.0e-1-d4.*t27.*5.0e-1+lend.*t20.*6.123233995736766e-17-lend.*t22.*5.0e-1-lend.*t24.*5.0e-1,0.0,t6+t9+t16+t17+t18+d3.*t13.*5.0e-1,-t26+t28+t29-d3.*t23.*5.0e-1-d4.*t27.*5.0e-1-lend.*t22.*5.0e-1,-d4.*t31-lend.*t33-d3.*sin(th2),t6+t16+t17+t18,t28+t29-d4.*t27.*5.0e-1-lend.*t22.*5.0e-1,-d4.*t31-lend.*t33,t6+t18,t29-lend.*t22.*5.0e-1,-lend.*t33,0.0,0.0,0.0],[3,5]);
