function Pend = MGD_end(d2,d3,d4,lend,r1,th1,th2,th3,th4)
%MGD_END
%    PEND = MGD_END(D2,D3,D4,LEND,R1,TH1,TH2,TH3,TH4)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    22-Mar-2017 16:24:59

t2 = -th1+th2+th3;
t3 = th1+th2+th3+th4;
t4 = th1+th2;
t5 = cos(th1);
t6 = sin(th1);
t7 = -th1+th2+th3+th4;
t8 = th1-th2;
t9 = th1+th2+th3;
Pend = [d2.*t5-lend.*t6.*6.123233995736766e-17+d4.*sin(t2).*5.0e-1+d3.*sin(t4).*5.0e-1-d3.*sin(t8).*5.0e-1+d4.*sin(t9).*5.0e-1+lend.*sin(t3).*5.0e-1+lend.*sin(t7).*5.0e-1;-d2.*t6-lend.*t5.*6.123233995736766e-17-d4.*cos(t2).*5.0e-1+d3.*cos(t4).*5.0e-1-d3.*cos(t8).*5.0e-1+d4.*cos(t9).*5.0e-1+lend.*cos(t3).*5.0e-1-lend.*cos(t7).*5.0e-1;lend.*3.749399456654644e-33+r1+d4.*cos(th2+th3)+d3.*cos(th2)+lend.*cos(th2+th3+th4)];
