function T0end = MGD_T0end(d2,d3,d4,lend,r1,th1,th2,th3,th4,th5)
%MGD_T0END
%    T0END = MGD_T0END(D2,D3,D4,LEND,R1,TH1,TH2,TH3,TH4,TH5)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    22-Mar-2017 16:25:00

t2 = th1+th2+th3+th4+th5;
t3 = th1-th5;
t4 = th1+th2+th3+th4-th5;
t5 = -th1+th2+th3+th4+th5;
t6 = th1+th5;
t7 = -th1+th2+th3+th4-th5;
t8 = th1+th2+th3+th4;
t9 = sin(t8);
t10 = sin(th1);
t11 = -th1+th2+th3+th4;
t12 = sin(t11);
t13 = sin(t2);
t14 = t13.*2.5e-1;
t15 = sin(t3);
t16 = t15.*(1.0./2.0);
t17 = sin(t4);
t18 = sin(t5);
t19 = t18.*2.5e-1;
t20 = sin(t6);
t21 = t20.*(1.0./2.0);
t22 = sin(t7);
t23 = cos(t2);
t24 = t23.*2.5e-1;
t25 = cos(t3);
t26 = cos(t4);
t27 = t26.*2.5e-1;
t28 = cos(t5);
t29 = t28.*2.5e-1;
t30 = cos(t6);
t31 = t30.*(1.0./2.0);
t32 = cos(t7);
t33 = t32.*2.5e-1;
t34 = cos(th1);
t35 = -th1+th2+th3;
t36 = cos(t8);
t37 = th1+th2;
t38 = cos(t11);
t39 = th1-th2;
t40 = th1+th2+th3;
t41 = th2+th3+th4+th5;
t42 = th2+th3+th4-th5;
t43 = th2+th3+th4;
t44 = cos(t43);
T0end = reshape([t24-t25.*(1.0./2.0)+t27+t29+t31+t33,-t14+t16-t17.*2.5e-1+t19-t21+t22.*2.5e-1,sin(t41).*(-5.0e-1)-sin(t42).*5.0e-1+sin(th5).*6.123233995736766e-17,0.0,t14+t16-t17.*2.5e-1+t19+t21-t22.*2.5e-1,t24+t25.*(1.0./2.0)-t27-t29+t31+t33,cos(t41).*5.0e-1-cos(t42).*5.0e-1-cos(th5).*6.123233995736766e-17,0.0,t9.*5.0e-1-t10.*6.123233995736766e-17+t12.*5.0e-1,t34.*(-6.123233995736766e-17)+t36.*5.0e-1-t38.*5.0e-1,t44+3.749399456654644e-33,0.0,d2.*t34+lend.*t9.*5.0e-1-lend.*t10.*6.123233995736766e-17+lend.*t12.*5.0e-1+d4.*sin(t35).*5.0e-1+d3.*sin(t37).*5.0e-1-d3.*sin(t39).*5.0e-1+d4.*sin(t40).*5.0e-1,-d2.*t10-lend.*t34.*6.123233995736766e-17+lend.*t36.*5.0e-1-lend.*t38.*5.0e-1-d4.*cos(t35).*5.0e-1+d3.*cos(t37).*5.0e-1-d3.*cos(t39).*5.0e-1+d4.*cos(t40).*5.0e-1,lend.*3.749399456654644e-33+r1+lend.*t44+d4.*cos(th2+th3)+d3.*cos(th2),1.0],[4,4]);
