%% Création de la figure de paramétres d'entrée

% Callbakc functions: callback_push_tableau(hObject,eventdata,f)


function f = creation_parametre_tableau(f)

%% Création de la figure de paramétres d'entrée
f.UserData.figure.entre = figure('name','Paramètres du tableau','NumberTitle','off',...
             'Position',[533 356 300 200],'menubar','none');
         
%% Text    
f.UserData.object.text.coord = uicontrol('Parent',f.UserData.figure.entre,...
    'Style','text','String','Coordonnées du centre de la grille',...
    'FontSize',11,'units','normalized','Position',[.1 .81 .8 .1]);

f.UserData.object.text.taille = uicontrol('Parent',f.UserData.figure.entre,...
    'Style','text','String','Taille de la case de la grille (mm):',...
    'FontSize',11,'units','normalized','Position',[.035 .42 .75 .1]);

f.UserData.object.text.Xcentre = uicontrol('Parent',f.UserData.figure.entre,...
    'Style','text','String','X (m):','FontSize',9,'units','normalized','Position',[.03 .67 .15 .07]);

f.UserData.object.text.Ycentre = uicontrol('Parent',f.UserData.figure.entre,...
    'Style','text','String','Y (m):','FontSize',9,'units','normalized','Position',[.33 .67 .15 .07]);

f.UserData.object.text.Zcentre = uicontrol('Parent',f.UserData.figure.entre,...
    'Style','text','String','Z (m):','FontSize',9,'units','normalized','Position',[.63 .67 .15 .07]);

%% Edit
f.UserData.object.edit.Xcentre = uicontrol('Parent',f.UserData.figure.entre,...
    'Style','edit','units','normalized','Position',[.17 .65 .13 .09]);

f.UserData.object.edit.Ycentre = uicontrol('Parent',f.UserData.figure.entre,...
    'Style','edit','units','normalized','Position',[.47 .65 .13 .09]);

f.UserData.object.edit.Zcentre = uicontrol('Parent',f.UserData.figure.entre,...
    'Style','edit','units','normalized','Position',[.77 .65 .13 .09]);

f.UserData.object.edit.taille = uicontrol('Parent',f.UserData.figure.entre,...
    'Style','edit','units','normalized','Position',[.79 .42 .13 .09]);

%% Checkbox
f.UserData.object.check.dessin = uicontrol('Parent',f.UserData.figure.entre,...
    'Style','checkbox','String','Je souhaite que le robot fasse le dessin de la grille',...
    'Value',0,'units','normalized','Position',[.05 .25 .9 .1]);

%% Pushbuttom
f.UserData.object.push.tab = uicontrol('Parent',f.UserData.figure.entre,...
    'Style','push','String','Envoyer','units','normalized',...
    'FontSize',11,'Position',[.37 .06 .25 .15],...
    'Callback',{@callback_push_tableau,f});

end