function Jv = Jacobian_youbot(D2,D3,D4,Lend,th1,th2,th3,th4)
%JACOBIAN_YOUBOT
%    JV = JACOBIAN_YOUBOT(D2,D3,D4,LEND,TH1,TH2,TH3,TH4)

% Jv = Jacobian_youbot(D2,D3,D4,Lend,th1,th2,th3,th4)
% Objectif: Calculer la matrice Jacobienne simplifiée (3x5) du robot Youbot KUKA, qui permet de tranformer les vitesses angulaires dans les vitesses linéaires 
% de l'outil
% Entrées: 	D2 = distance dans l'axe X_1 des repéres 2 au repère 1
%			D3 = distance dans l'axe X_2 des repéres 3 au repère 2
%			D4 = distance dans l'axe X_3 des repéres 4 au repère 3
%			Lend = taille de l'outil du robot
%			th1 = position angulaire de l'axe 1
%			th2 = position angulaire de l'axe 2
%			th3 = position angulaire de l'axe 3
%			th4 = position angulaire de l'axe 4
% Sortie: 	Jv = la matrice Jacobienne simplifiée du robot

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    13-Jun-2017 22:43:01

t2 = conj(Lend);
t3 = th1+th2+th3+th4;
t4 = cos(t3);
t5 = th1-th2-th3-th4;
t6 = cos(t5);
t7 = t6.*5.0e-1;
t8 = th1-th2;
t9 = sin(t8);
t10 = t9.*5.0e-1;
t11 = th1+th2;
t12 = sin(t11);
t13 = t12.*5.0e-1;
t14 = th1+th2+th3;
t15 = sin(t14);
t16 = t15.*5.0e-1;
t17 = th1-th2-th3;
t18 = sin(t17);
t19 = t18.*5.0e-1;
t20 = t4.*5.0e-1;
t21 = t7+t20;
t22 = t16-t19;
t23 = sin(th1);
t24 = cos(th1);
t25 = cos(t8);
t26 = t25.*5.0e-1;
t27 = cos(t11);
t28 = t27.*5.0e-1;
t29 = sin(t3);
t30 = sin(t5);
t31 = t30.*5.0e-1;
t32 = cos(t14);
t33 = t32.*5.0e-1;
t34 = cos(t17);
t35 = t34.*5.0e-1;
t36 = t29.*5.0e-1;
t37 = t31+t36;
t38 = t33-t35;
t39 = D4.*t38;
t40 = th2+th3+th4;
t41 = sin(t40);
t42 = th2+th3;
t43 = cos(t42);
t44 = D4.*t43;
Jv = reshape([-D2.*t23+t2.*(t4.*(-5.0e-1)+t7+t24.*6.123233995736766e-17)-D3.*(t10+t13)-D4.*(t16+t19),D2.*t24+t2.*(t23.*6.123233995736766e-17-t29.*5.0e-1+t31)+D3.*(t26+t28)+D4.*(t33+t35),0.0,-D4.*t22-t2.*t21+D3.*(t10-t13),t39-t2.*t37-D3.*(t26-t28),t44-t2.*t41+D3.*cos(th2),-D4.*t22-t2.*t21,t39-t2.*t37,t44-t2.*t41,-t2.*t21,-t2.*t37,-t2.*t41,0.0,0.0,0.0],[3, 5]);
