%% Création de la figure de paramètres d'utilisateurs

% Callbakc functions: callback_push_utilisateur(hObject,eventdata,f)

function f = creation_parametre_utilisateurs(f)

%% Création de la figure de paramétres d'entrée
f.UserData.figure.utilisateur = figure('name','Utilisateurs','NumberTitle','off',...
             'Position',[533 330 300 250],'menubar','none');
         
%% Panel    
f.UserData.object.pan.util1 = uipanel('Parent',f.UserData.figure.utilisateur,...
    'Title','Joueur 1','FontWeight','bold',...
    'FontSize',11,'units','normalized','Position',[.06 .56 .88 .40]);

f.UserData.object.pan.util2 = uipanel('Parent',f.UserData.figure.utilisateur,...
    'Title','Joueur 2','FontWeight','bold',...
    'FontSize',11,'units','normalized','Position',[.06 .19 .88 .35]);

%% Text
f.UserData.object.text.name1 = uicontrol('Parent',f.UserData.object.pan.util1,...
    'Style','text','String','Prénom: ',...
    'FontSize',11,'units','normalized','Position',[.21 .74 .3 .2]);

f.UserData.object.text.name2 = uicontrol('Parent',f.UserData.object.pan.util2,...
    'Style','text','String','Prénom: ',...
    'FontSize',11,'units','normalized','Position',[.21 .68 .3 .25]);

f.UserData.object.text.commence = uicontrol('Parent',f.UserData.object.pan.util1,...
    'Style','text','String','Le joueur 1 sera le premier à jouer',...
    'FontSize',8,'units','normalized','Position',[.15 .05 .7 .15]);

f.UserData.object.text.ident1= uicontrol('Parent',f.UserData.object.pan.util1,...
    'Style','text','String','Identificateur: ',...
    'FontSize',11,'units','normalized','Position',[.13 .38 .35 .2]);

f.UserData.object.text.ident2= uicontrol('Parent',f.UserData.object.pan.util2,...
    'Style','text','String','Identificateur: ',...
    'FontSize',11,'units','normalized','Position',[.13 .21 .35 .25]);

%% Edit
f.UserData.object.edit.name1 = uicontrol('Parent',f.UserData.object.pan.util1,...
    'Style','edit','units','normalized','Position',[.50 .70 .35 .24]);

f.UserData.object.edit.name2 = uicontrol('Parent',f.UserData.object.pan.util2,...
    'Style','edit','units','normalized','Position',[.50 .63 .35 .30]);

%% Radio button
f.UserData.object.button.group1 = uibuttongroup('Parent',f.UserData.object.pan.util1,...
    'Visible','on', 'units','normalized',...
     'Position',[.50 .31 .35 .27],'SelectionChangedFcn',{@callback_button_group1,f});
              
f.UserData.object.button.group1_X= uicontrol('Parent',f.UserData.object.button.group1,...
    'Style','radiobutton','String','X','units','normalized',...
    'Position',[.1 .19 .8 .7]);

f.UserData.object.button.group1_O = uicontrol('Parent',f.UserData.object.button.group1,...
    'Style','radiobutton','String','O','units','normalized',...
    'Position',[.6 .19 .8 .7]);

f.UserData.object.button.group2 = uibuttongroup('Parent',f.UserData.object.pan.util2,...
    'Visible','on', 'units','normalized',...
     'Position',[.50 .15 .35 .32],'SelectionChangedFcn',{@callback_button_group2,f});
              
f.UserData.object.button.group2_O = uicontrol('Parent',f.UserData.object.button.group2,...
    'Style','radiobutton','String','O','units','normalized',...
    'Position',[.6 .15 .3 .7]);

f.UserData.object.button.group2_X= uicontrol('Parent',f.UserData.object.button.group2,...
    'Style','radiobutton','String','X','units','normalized',...
    'Position',[.1 .15 .3 .7]);

%% Pushbuttom
f.UserData.object.push.util = uicontrol('Parent',f.UserData.figure.utilisateur,...
    'Style','push','String','Envoyer','units','normalized',...
    'FontSize',11,'Position',[.375 .05 .25 .10],...
    'Callback',{@callback_push_utilisateur,f});

end