function T0end = MGD_T0end(D1,D2,D3,D4,Lend,R1,th1,th2,th3,th4,th5)
%MGD_T0END
%    T0END = MGD_T0END(D1,D2,D3,D4,LEND,R1,TH1,TH2,TH3,TH4,TH5)

% T0end = MGD_T0end(D1,D2,D3,D4,Lend,R1,th1,th2,th3,th4,th5)
% Objectif: Calcul du modèle géometrique direct du robot.
% Entrées: 	D1 = distance dans l'axe X_0 du repère 1 au repère 0
%			D2 = distance dans l'axe X_1 du repère 2 au repère 1
%			D3 = distance dans l'axe X_2 du repère 3 au repère 2
%			D4 = distance dans l'axe X_3 du repère 4 au repère 3
%			Lend = taille de l'outil du robot
%			R1 = distance dans l'axe Z_0 du repère 1 au repère 0
%			th1 = position angulaire de l'axe 1
%			th2 = position angulaire de l'axe 2
%			th3 = position angulaire de l'axe 3
%			th4 = position angulaire de l'axe 4
%			th5 = position angulaire de l'axe 5
% Sortie: 	Pend = la matrice homogène de la configuration (position et orientation) de l'outil du robot

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    13-Jun-2017 22:42:59

t2 = sin(th5);
t3 = th1+th2+th3+th4;
t4 = th1-th2-th3-th4;
t5 = cos(th5);
t6 = sin(th1);
t7 = cos(t3);
t8 = t7.*5.0e-1;
t9 = cos(t4);
t10 = t9.*5.0e-1;
t11 = t8+t10;
t12 = sin(t3);
t13 = t12.*5.0e-1;
t14 = sin(t4);
t16 = t14.*5.0e-1;
t15 = t13-t16;
t17 = t6.*6.123233995736766e-17;
t18 = -t13+t16+t17;
t19 = cos(th1);
t20 = t8-t10;
t21 = t13+t16;
t22 = th1-th2;
t23 = th1+th2;
t24 = conj(Lend);
t25 = th1+th2+th3;
t26 = th1-th2-th3;
t27 = th2+th3+th4;
t28 = cos(t27);
t29 = sin(t27);
t30 = t28+3.749399456654644e-33;
T0end = reshape([-t2.*t6+t5.*t11-t2.*t15.*6.123233995736766e-17,t2.*t19+t2.*t20.*6.123233995736766e-17+t5.*t21,t2.*(-6.123233995736766e-17)+t2.*t28.*6.123233995736766e-17+t5.*t29,0.0,-t5.*t6-t2.*t11-t5.*t15.*6.123233995736766e-17,-t2.*t21+t5.*t19+t5.*t20.*6.123233995736766e-17,t5.*(-6.123233995736766e-17)-t2.*t29+t5.*t28.*6.123233995736766e-17,0.0,t18,t8-t10-t19.*6.123233995736766e-17,t30,0.0,D1+D2.*t19+t18.*t24+D3.*(cos(t22).*5.0e-1+cos(t23).*5.0e-1)+D4.*(cos(t25).*5.0e-1+cos(t26).*5.0e-1),D2.*t6-t24.*(-t8+t10+t19.*6.123233995736766e-17)+D3.*(sin(t22).*5.0e-1+sin(t23).*5.0e-1)+D4.*(sin(t25).*5.0e-1+sin(t26).*5.0e-1),R1+t24.*t30+D4.*sin(th2+th3)+D3.*sin(th2),1.0],[4, 4]);
